extension Theme {
    public static let nibLight = Theme(
        id: "nib-light",
        name: "Nib Light",
        appearance: .light,
        tokens: [
            ThemeToken.editorBackground.rawValue: "#F5F5F7",
            ThemeToken.editorForeground.rawValue: "#1D1D1F",
            ThemeToken.gutterBackground.rawValue: "#F5F5F7",
            ThemeToken.gutterForeground.rawValue: "#86868B",
            ThemeToken.cursor.rawValue: "#1D1D1F",
            ThemeToken.selection.rawValue: "#007AFF40",
            ThemeToken.currentLine.rawValue: "#0000000A",
            ThemeToken.matchingBracket.rawValue: "#007AFF33",
            ThemeToken.searchMatch.rawValue: "#FFD60A66",
            ThemeToken.diffAddition.rawValue: "#34C75933",
            ThemeToken.diffRemoval.rawValue: "#FF3B3033",
            ThemeToken.diffModification.rawValue: "#FF9F0A33",
            ThemeToken.diagnosticError.rawValue: "#FF3B30",
            ThemeToken.diagnosticWarning.rawValue: "#FF9F0A",
            ThemeToken.diagnosticInfo.rawValue: "#007AFF",
            ThemeToken.diagnosticHint.rawValue: "#86868B",
            ThemeToken.aiSuggestion.rawValue: "#8E8E93",
            ThemeToken.overlayBackground.rawValue: "#FFFFFFF2",
            ThemeToken.overlayForeground.rawValue: "#1D1D1F",
            ThemeToken.overlayBorder.rawValue: "#00000014",
            ThemeToken.paletteBackground.rawValue: "#FFFFFFF5",
            ThemeToken.paletteForeground.rawValue: "#1D1D1F",
            ThemeToken.paletteSelection.rawValue: "#007AFF22",
            ThemeToken.syntaxComment.rawValue: "#86868B",
            ThemeToken.syntaxKeyword.rawValue: "#9B2393",
            ThemeToken.syntaxString.rawValue: "#C41A16",
            ThemeToken.syntaxNumber.rawValue: "#1C00CF",
            ThemeToken.syntaxFunction.rawValue: "#326D74",
            ThemeToken.syntaxType.rawValue: "#0B4F79",
            ThemeToken.syntaxVariable.rawValue: "#1D1D1F",
            ThemeToken.syntaxPunctuation.rawValue: "#636366",
            ThemeToken.markdownHeading.rawValue: "#0B4F79",
            ThemeToken.markdownLink.rawValue: "#007AFF",
        ],
        syntax: defaultSyntaxMap
    )

    public static let nibDark = Theme(
        id: "nib-dark",
        name: "Nib Dark",
        appearance: .dark,
        tokens: [
            ThemeToken.editorBackground.rawValue: "#1C1C1E",
            ThemeToken.editorForeground.rawValue: "#F5F5F7",
            ThemeToken.gutterBackground.rawValue: "#1C1C1E",
            ThemeToken.gutterForeground.rawValue: "#98989D",
            ThemeToken.cursor.rawValue: "#F5F5F7",
            ThemeToken.selection.rawValue: "#0A84FF55",
            ThemeToken.currentLine.rawValue: "#FFFFFF0F",
            ThemeToken.matchingBracket.rawValue: "#0A84FF44",
            ThemeToken.searchMatch.rawValue: "#FFD60A55",
            ThemeToken.diffAddition.rawValue: "#30D15833",
            ThemeToken.diffRemoval.rawValue: "#FF453A33",
            ThemeToken.diffModification.rawValue: "#FFD60A33",
            ThemeToken.diagnosticError.rawValue: "#FF453A",
            ThemeToken.diagnosticWarning.rawValue: "#FFD60A",
            ThemeToken.diagnosticInfo.rawValue: "#0A84FF",
            ThemeToken.diagnosticHint.rawValue: "#98989D",
            ThemeToken.aiSuggestion.rawValue: "#8E8E93",
            ThemeToken.overlayBackground.rawValue: "#2C2C2EF2",
            ThemeToken.overlayForeground.rawValue: "#F5F5F7",
            ThemeToken.overlayBorder.rawValue: "#FFFFFF1A",
            ThemeToken.paletteBackground.rawValue: "#2C2C2EF5",
            ThemeToken.paletteForeground.rawValue: "#F5F5F7",
            ThemeToken.paletteSelection.rawValue: "#0A84FF33",
            ThemeToken.syntaxComment.rawValue: "#8E8E93",
            ThemeToken.syntaxKeyword.rawValue: "#FF7AB2",
            ThemeToken.syntaxString.rawValue: "#FF8170",
            ThemeToken.syntaxNumber.rawValue: "#D9C97C",
            ThemeToken.syntaxFunction.rawValue: "#78C2B3",
            ThemeToken.syntaxType.rawValue: "#6BDFFF",
            ThemeToken.syntaxVariable.rawValue: "#F5F5F7",
            ThemeToken.syntaxPunctuation.rawValue: "#A1A1A6",
            ThemeToken.markdownHeading.rawValue: "#6BDFFF",
            ThemeToken.markdownLink.rawValue: "#0A84FF",
        ],
        syntax: defaultSyntaxMap
    )

    public static let builtIn: [Theme] = [nibLight, nibDark]

    private static let defaultSyntaxMap: [String: String] = [
        "comment": ThemeToken.syntaxComment.rawValue,
        "keyword": ThemeToken.syntaxKeyword.rawValue,
        "string": ThemeToken.syntaxString.rawValue,
        "number": ThemeToken.syntaxNumber.rawValue,
        "function": ThemeToken.syntaxFunction.rawValue,
        "type": ThemeToken.syntaxType.rawValue,
        "variable": ThemeToken.syntaxVariable.rawValue,
        "punctuation": ThemeToken.syntaxPunctuation.rawValue,
        "heading": ThemeToken.markdownHeading.rawValue,
        "link": ThemeToken.markdownLink.rawValue,
    ]
}
